-- ============================================================
-- Altbieratlas — Seed data
-- ============================================================
-- Styles, glossary, breweries, prices and events for every
-- deployment (dev, staging and production).
-- All statements are idempotent (INSERT OR IGNORE).
-- ============================================================

-- Beer styles
INSERT OR IGNORE INTO styles (id, name, abv, ibu, color, tasting_de, tasting_en) VALUES
  ('uerige-alt',    'Uerige Alt',          4.7,  52, '#7b3a13',
    'Kräftig herb, würzig, trockener Abgang. Eine der bitteren unter den Düsseldorfer Alts.',
    'Firmly bitter, spicy, dry finish. One of the more bitter Düsseldorf Alts.'),
  ('sticke',        'Uerige Sticke',        6.0,  65, '#5b2409',
    'Stärker eingebraut, malzig-komplex, intensivere Hopfengabe. Nur zweimal jährlich ausgeschenkt.',
    'Stronger brew, malt-complex, more intense hopping. Only served twice a year.'),
  ('doppelsticke',  'Uerige Doppelsticke',  8.5, 70, '#3d1606',
    'Fast portweinartig, reich, komplex, mit langer Reife. Für die seltenen Anlässe.',
    'Almost port-like, rich, complex, long-aged. For the rare occasions.'),
  ('fuechschen-alt','Füchschen Alt',        4.5,  38, '#8a4a1f',
    'Malzbetont, vollmundig, weich. Eines der zugänglichsten Düsseldorfer Alts.',
    'Malt-forward, full-bodied, soft. One of the most approachable Düsseldorf Alts.'),
  ('schumacher-alt','Schumacher Alt',       4.6,  32, '#9b5226',
    'Mild, rund, gut trinkbar. Der Klassiker für den langen Abend.',
    'Mild, round, highly drinkable. The classic for a long evening.'),
  ('schluessel-alt','Schlüssel Alt',        5.0,  35, '#823c13',
    'Leicht herb, ausgewogen, trocken. Sehr traditioneller Stil.',
    'Lightly bitter, balanced, dry. Very traditional style.'),
  ('kuerzer-alt',   'Kürzer Alt',           4.8,  34, '#8f461b',
    'Frisch, hell-bernsteinfarben, mit leichter Citrusnote vom offen gekochten Sud.',
    'Fresh, light amber, with a gentle citrus note from the open-boil wort.'),
  ('alaskan-amber', 'Alaskan Amber',        5.3,  18, '#a55b24',
    'Amerikanische Alt-Interpretation: malzbetont, karamellig, weicher als die Düsseldorfer Originale.',
    'American take on Alt: malt-forward, caramel, softer than the Düsseldorf originals.'),
  ('koenigshof-alt','Königshof Alt',        4.9,  28, '#8c4a1a',
    'Mild-malzig, niederrheinisch weich. Klassisch für die Region.',
    'Mild-malty, soft in the Lower-Rhine style. Regional classic.'),
  ('hannen-alt',    'Hannen Alt',           4.8,  30, '#8c4820',
    'Industriell gebraut, aber klassisch profiliert. Die wohl bekannteste Alt-Marke außerhalb Düsseldorfs.',
    'Industrially brewed but classically profiled. Likely the best-known Alt brand outside Düsseldorf.'),
  ('long-trail-ale','Long Trail Ale',       4.6,  25, '#a56030',
    'Vermonter Interpretation: malzig, süßlich, mit amerikanischem Hopfencharakter.',
    'Vermont take: malty, mildly sweet, with American hop character.');

-- Glossary
INSERT OR IGNORE INTO glossary (term, definition_de, definition_en) VALUES
  ('Altbier',
    'Obergäriges, dunkel-bernsteinfarbenes Bier aus dem Rheinland. "Alt" verweist auf die alte, obergärige Brauart (im Gegensatz zum später aufgekommenen, untergärigen Lager).',
    'A top-fermented, amber-to-copper beer from the Rhineland. "Alt" refers to the old, top-fermenting brewing method (as opposed to later bottom-fermented lagers).'),
  ('Köbes',
    'Die traditionelle Bedienung in Düsseldorfer Hausbrauereien. Typischerweise in blauer Schürze, wortkarg, direkt, oft mit trockenem Humor. Ein Köbes ist keine Servicekraft im modernen Sinn — er ist Teil des Rituals.',
    'The traditional server in Düsseldorf brewpubs. Typically in a blue apron, taciturn, direct, often with a dry wit. A Köbes is not a service worker in the modern sense — he is part of the ritual.'),
  ('Sticke',
    'Ein stärker eingebrautes, hopfenbetonteres Alt. Im Uerige wird es nur zweimal jährlich ausgeschenkt — im Januar und Oktober, jeweils am dritten Dienstag.',
    'A stronger, more hop-forward Alt. At Uerige it is served only twice a year — on the third Tuesday of January and October.'),
  ('Doppelsticke',
    'Die noch stärkere Variante der Sticke, rund 8,5 % Alkohol. Ursprünglich für den Export in die USA gebraut.',
    'An even stronger variant of Sticke, around 8.5% ABV. Originally brewed for export to the USA.'),
  ('Kranz',
    'Das runde Holztablett, auf dem der Köbes die 0,25-l-Gläser stapelt. Fasst typisch 12 bis 15 Gläser.',
    'The round wooden tray the Köbes uses to stack 0.25 l glasses. Typically holds 12 to 15 glasses.'),
  ('Strichliste',
    'Der Bierdeckel, auf dem der Köbes für jedes neue Alt einen Strich macht. Abgerechnet wird am Ende — keiner prüft nach.',
    'The coaster on which the Köbes tallies a stroke for each new Alt. Settled at the end — nobody double-checks.'),
  ('Latzenbier',
    'Ein stärker eingebrautes Saison-Alt bei Schumacher, das vom hochgelegten Latzen-Fass gezapft wird. Traditionell im Herbst.',
    'A stronger seasonal Alt at Schumacher, tapped from an elevated Latzen barrel. Traditionally in autumn.'),
  ('Obergärig',
    'Bezeichnet die Gärweise: Hefe, die bei wärmeren Temperaturen (15-20 °C) oben auf dem Sud arbeitet. Führt zu fruchtigeren Aromen als untergärige Hefen.',
    'Describes the fermentation: yeast that works at warmer temperatures (15-20 °C) on top of the wort. Produces fruitier aromas than bottom-fermenting yeasts.'),
  ('Hausbrauerei',
    'Eine Brauerei, die direkt im angeschlossenen Gastraum ausschenkt. Die vier klassischen Düsseldorfer Hausbrauereien sind Uerige, Füchschen, Schumacher und Schlüssel.',
    'A brewery that pours directly in its attached taproom. The four classic Düsseldorf brewpubs are Uerige, Füchschen, Schumacher and Schlüssel.'),
  ('Rheinisches Reinheitsgebot',
    'Kein offizielles Gesetz, sondern ein augenzwinkerndes Selbstverständnis: ein richtiges Alt braucht nichts außer Wasser, Gerste, Hopfen und obergäriger Hefe — und einen Köbes, der es hinstellt.',
    'Not an actual law, but a tongue-in-cheek self-understanding: a proper Alt needs nothing but water, barley, hops and top-fermenting yeast — and a Köbes to set it down.');

-- Breweries / taprooms / retail
INSERT OR IGNORE INTO breweries (id, name, short_name, type, city, country, address, lat, lng, founded, website, description_de, description_en, verified, status) VALUES
  ('uerige', 'Brauerei im Uerige', 'Uerige', 'hausbrauerei', 'Düsseldorf', 'DE',
    'Berger Straße 1, 40213 Düsseldorf', 51.2253, 6.7722, 1862, 'https://uerige.de',
    'Eine der vier klassischen Düsseldorfer Hausbrauereien in der Altstadt. Bekannt für kräftig-herbes, würziges Alt und die halbjährliche Sticke-Ausschank.',
    'One of the four classic Düsseldorf brewpubs in the old town. Known for a firm, bitter, spicy Alt and its biannual Sticke release.', 1, 'approved'),
  ('fuechschen', 'Brauerei Füchschen', 'Füchschen', 'hausbrauerei', 'Düsseldorf', 'DE',
    'Ratinger Straße 28, 40213 Düsseldorf', 51.2278, 6.7715, 1848, 'https://fuechschen.de',
    'Familiengeführte Hausbrauerei, bekannt für ein malzbetontes, vollmundiges Alt und die legendäre Weihnachts-Silvester-Stimmung.',
    'Family-run brewpub known for a malty, full-bodied Alt and its legendary Christmas-New-Year atmosphere.', 1, 'approved'),
  ('schumacher', 'Brauerei Schumacher', 'Schumacher', 'hausbrauerei', 'Düsseldorf', 'DE',
    'Oststraße 123, 40210 Düsseldorf', 51.2224, 6.7912, 1838, 'https://schumacher-alt.de',
    'Die älteste der Düsseldorfer Hausbrauereien. Mildes, gut trinkbares Schumacher Alt seit 1838.',
    'The oldest of the Düsseldorf brewpubs. A mild, highly drinkable Schumacher Alt since 1838.', 1, 'approved'),
  ('schluessel', 'Brauerei zum Schlüssel', 'Schlüssel', 'hausbrauerei', 'Düsseldorf', 'DE',
    'Bolkerstraße 41-47, 40213 Düsseldorf', 51.2268, 6.7728, 1850, 'https://zumschluessel.de',
    'Traditionsreiche Hausbrauerei an der Bolkerstraße, im Herzen der Altstadt. Ausgewogenes, leicht herbes Alt.',
    'Heritage brewpub on Bolker Straße, in the heart of the old town. A balanced, gently bitter Alt.', 1, 'approved'),
  ('kuerzer', 'Brauerei Kürzer', 'Kürzer', 'hausbrauerei', 'Düsseldorf', 'DE',
    'Kurze Straße 18-20, 40213 Düsseldorf', 51.2262, 6.7733, 2010, 'https://brauerei-kuerzer.de',
    'Die jüngste der Düsseldorfer Altstadt-Hausbrauereien. Offene Braukessel mitten im Gastraum.',
    'The youngest of Düsseldorf''s old-town brewpubs. Open brewing kettles right in the taproom.', 1, 'approved'),
  ('zum-schlueffken', 'Zum Schlüffken', 'Schlüffken', 'gastronomie', 'Düsseldorf', 'DE',
    'Flinger Straße 1, 40213 Düsseldorf', 51.2271, 6.774, NULL, NULL,
    'Urige Altstadt-Kneipe mit Uerige Alt vom Fass. Klassische Köbes-Bedienung.',
    'Classic old-town pub serving Uerige Alt on tap. Traditional Köbes service.', 1, 'approved'),
  ('koenigshof', 'Privatbrauerei Königshof', 'Königshof', 'hausbrauerei', 'Krefeld', 'DE',
    'Untergath 70, 47805 Krefeld', 51.3172, 6.5603, 1830, 'https://privatbrauerei-koenigshof.de',
    'Niederrheinische Privatbrauerei mit einem milderen Alt im niederrheinischen Stil.',
    'Lower-Rhine private brewery with a milder Alt in the Niederrhein style.', 1, 'approved'),
  ('hannen', 'Hannen Brauerei', 'Hannen', 'hausbrauerei', 'Mönchengladbach', 'DE',
    'Bismarckstraße 115, 41061 Mönchengladbach', 51.1805, 6.4428, 1725, NULL,
    'Traditionsmarke, heute unter Carlsberg-Dach. Eines der bekanntesten Alt-Biere außerhalb Düsseldorfs.',
    'Heritage brand, now under Carlsberg. One of the best-known Alts outside Düsseldorf.', 1, 'approved'),
  ('malzmuehle-alt', 'Alt-Eck', 'Alt-Eck Köln', 'gastronomie', 'Köln', 'DE',
    'Weidengasse 20, 50668 Köln', 50.9452, 6.9606, NULL, NULL,
    'Exotisch im Kölsch-Land: eine Kneipe mit echtem Alt-Ausschank. Nicht jedermanns Sache.',
    'Exotic in Kölsch country: a pub actually serving Alt. Not for everyone.', 0, 'approved'),
  ('alaskan-brewing', 'Alaskan Brewing Co.', 'Alaskan', 'hausbrauerei', 'Juneau', 'US',
    '5429 Shaune Drive, Juneau, AK', 58.358, -134.554, 1986, 'https://alaskanbeer.com',
    'US-Craft-Brauerei mit einem sehr gelungenen Alt nach Düsseldorfer Vorbild — mehrfach ausgezeichnet.',
    'US craft brewery with a highly regarded Alt in the Düsseldorf tradition — multiple award winner.', 1, 'approved'),
  ('long-trail', 'Long Trail Brewing', 'Long Trail', 'hausbrauerei', 'Bridgewater Corners', 'US',
    '5520 US-4, Bridgewater Corners, VT', 43.6, -72.7614, 1989, 'https://longtrail.com',
    'Vermonter Brauerei mit einem Flagship-Altbier im rheinischen Stil.',
    'Vermont brewery whose flagship is a Rhenish-style Altbier.', 1, 'approved'),
  ('bruery-terreux', 'The Bruery', 'Bruery', 'hausbrauerei', 'Placentia', 'US',
    '717 Dunn Way, Placentia, CA', 33.8814, -117.8626, 2008, 'https://thebruery.com',
    'Kalifornische Craft-Brauerei mit gelegentlichen Altbier-Interpretationen.',
    'California craft brewery with occasional Altbier releases.', 0, 'approved'),
  ('marble-nl', 'Brouwerij Rückerl', 'Rückerl', 'hausbrauerei', 'Arnhem', 'NL',
    'Westervoortsedijk 73, Arnhem', 51.9804, 5.9388, 2014, NULL,
    'Niederländische Hausbrauerei mit einem Altbier nach niederrheinischer Tradition.',
    'Dutch brewpub with an Altbier in the Niederrhein tradition.', 0, 'approved'),
  ('tokyo-alt', 'Ushitora Brewery', 'Ushitora', 'hausbrauerei', 'Tokyo', 'JP',
    '2-9-3 Sangenjaya, Setagaya, Tokyo', 35.6434, 139.6713, 2014, NULL,
    'Tokioter Craft-Brauerei, die immer wieder ein Altbier ins Sortiment nimmt.',
    'Tokyo craft brewery that regularly puts an Altbier on the lineup.', 0, 'approved');

-- Style assignments
INSERT OR IGNORE INTO brewery_styles (brewery_id, style_id) VALUES
  ('uerige',          'uerige-alt'),
  ('uerige',          'sticke'),
  ('uerige',          'doppelsticke'),
  ('fuechschen',      'fuechschen-alt'),
  ('schumacher',      'schumacher-alt'),
  ('schluessel',      'schluessel-alt'),
  ('kuerzer',         'kuerzer-alt'),
  ('zum-schlueffken', 'uerige-alt'),
  ('koenigshof',      'koenigshof-alt'),
  ('hannen',          'hannen-alt'),
  ('malzmuehle-alt',  'fuechschen-alt'),
  ('alaskan-brewing', 'alaskan-amber'),
  ('long-trail',      'long-trail-ale');

-- Prices
INSERT OR IGNORE INTO prices (brewery_id, date, size, price, source, status) VALUES
  ('uerige',          '2026-04-15', '0.25l', 2.7, 'on-site',  'approved'),
  ('uerige',          '2026-04-10', '0.25l', 2.7, 'on-site',  'approved'),
  ('uerige',          '2026-03-28', '0.25l', 2.7, 'website',  'approved'),
  ('uerige',          '2025-11-05', '0.25l', 2.5, 'on-site',  'approved'),
  ('uerige',          '2025-06-20', '0.25l', 2.5, 'on-site',  'approved'),
  ('fuechschen',      '2026-04-12', '0.25l', 2.6, 'on-site',  'approved'),
  ('fuechschen',      '2026-02-14', '0.25l', 2.6, 'on-site',  'approved'),
  ('fuechschen',      '2025-09-01', '0.25l', 2.4, 'on-site',  'approved'),
  ('schumacher',      '2026-04-08', '0.25l', 2.5, 'on-site',  'approved'),
  ('schumacher',      '2026-01-20', '0.25l', 2.5, 'on-site',  'approved'),
  ('schluessel',      '2026-04-14', '0.25l', 2.6, 'on-site',  'approved'),
  ('schluessel',      '2025-12-01', '0.25l', 2.5, 'on-site',  'approved'),
  ('kuerzer',         '2026-04-16', '0.25l', 2.8, 'on-site',  'approved'),
  ('kuerzer',         '2026-03-01', '0.25l', 2.7, 'on-site',  'approved'),
  ('koenigshof',      '2026-04-02', '0.5l',  3.4, 'retail',   'approved'),
  ('hannen',          '2026-03-15', '0.5l',  2.9, 'retail',   'approved'),
  ('alaskan-brewing', '2026-03-22', '0.5l',  5.2, 'on-site',  'approved'),
  ('long-trail',      '2026-03-18', '0.5l',  4.8, 'on-site',  'approved'),
  ('tokyo-alt',       '2026-04-01', '0.33l', 6.5, 'on-site',  'approved'),
  ('zum-schlueffken', '2026-04-12', '0.25l', 2.7, 'on-site',  'approved'),
  ('malzmuehle-alt',  '2026-03-05', '0.25l', 3.0, 'on-site',  'approved');

-- Events
INSERT OR IGNORE INTO events (id, title_de, title_en, brewery_id, date, description_de, description_en, status) VALUES
  ('sticke-herbst-2026', 'Sticke-Ausschank Uerige (Herbst)', 'Sticke release at Uerige (autumn)',
    'uerige', '2026-10-20',
    'Der traditionelle Sticke-Anstich im Uerige. Ein Termin für Alt-Liebhaber weltweit.',
    'The traditional Sticke tapping at Uerige. A bucket-list date for Alt lovers worldwide.', 'approved'),
  ('altbierrunde-2026', 'Düsseldorfer Altbierrunde', 'Düsseldorf Altbier round',
    NULL, '2026-05-18',
    'Gemeinschaftliche Tour durch die vier klassischen Hausbrauereien der Altstadt.',
    'Group tour through the four classic old-town brewpubs.', 'approved'),
  ('latzenbier-2026', 'Schumacher Latzenbier-Saison', 'Schumacher Latzenbier season',
    'schumacher', '2026-11-05',
    'Das stärker eingebraute Latzenbier wird direkt aus dem hochgestellten Latzen-Fass gezapft.',
    'The stronger Latzenbier is served directly from the elevated barrel.', 'approved');
